### ISSUE TITLE
Plugin installs itself to root of modules folder instead of 'modules/_protected'.

### ISSUE THREAD

**Issue by jmietola** [Siteimprove/CMS-plugin-Episerver#1]
I installed CMS-plugin-Episerver trough nuget http://nuget.episerver.com/en/OtherPages/Package/?packageId=SiteImprove.EPiServer.Plugin. All other modules are located /modules/_protected/  but this was located in root of modules. Now when I try to open SiteImprove from Episerver admin tool section I got content not found error.

https://world.episerver.com/documentation/Items/Developers-Guide/Episerver-CMS/9/add-ons/Developing-Add-ons/

Public add-ons have a default virtual path starting from ~/modules/<package ID>/.
Protected add-on files are located by default in ~/modules/_protected/<package ID>/.

**Comment by nma1o1** [comment]
fix have been made, Currently awaiting Episerver approval.

**Comment by CasperTDK** [comment]
Hi @jmietola 

We have moved the plugin to _protected/

The latest version have been approved by episerver:
http://nuget.episerver.com/en/OtherPages/Package/?packageId=SiteImprove.EPiServer.Plugin

Please let me know if you still experience issues

**Comment by jmietola** [comment]
Thank you! seems to be working. Although I had to enable EPiServer CMS UI AspNetIdentity OWIN authentication for project. This can be validated by trying to install add-on to almost blank Episerver project instead of alloy.
