### ISSUE TITLE
Error in routing

### ISSUE THREAD

**Issue by btsvennes** [Siteimprove/CMS-plugin-Episerver#3]
In PackageInitializer.cs the route is defined as "siteimprove/{action}", but the one attempted from Episerver Admin (when clicking siteimprove under Tools) is "siteimproveadmin/index", which fails.

**Comment by emilssonn** [comment]
I did some digging and found the following: 
The route "siteimprove/{action}" is for the dojo plug-in and is working. The route "siteimproveadmin" is the route that should be used for the admin plug-in and is not working. The reason for it not working is that the route also needs to be registred in a initialization module, in the same way as the route "siteimprove/{action}".

If you install this package in a alloy site with the default implementation of asp.net identity for episerver included the route will work. The reason for this is the method "AddRoute" in the class "AdministratorRegistrationPage" in the alloy project.

I can make pull request for this if you want. The solution should simply be to add the following after the "siteimprove/{action}" route registration:
`RouteTable.Routes.MapRoute(
  "SiteimproveAdmin",
  "siteimproveAdmin",
  new { controller = "SiteimproveAdmin", action = "Index" });`

**Comment by CasperTDK** [comment]
Thanks! I see your point. I have tested your routing and it works. A new nuget package will be out in http://nuget.episerver.com/ soon (already submitted).
