### ISSUE TITLE
Plugin breaks Episerver UI 

### ISSUE THREAD

**Issue by KevinJCandlert** [Siteimprove/CMS-plugin-Episerver#5]
A user without any of the authorized roles (Administrators, WebAdmins, CmsAdmins, SiteimproveAdmins) won't be able to use the Episerver UI after siteimprove.js:110 executes the ajax request to get a token.
```
       /**
         * Request token from backoffice and sends request to Siteimprove
         */
        pushSi: function (method, url) {
            var si = window._si || [];

            request.get('/siteimprove/token', { handleAs: 'json' })
                .then(function (response) {

                    // Send of to siteimprove
                    si.push([method, url, response, function () {
                        console.log('SiteImprove pass: ' + method + ' - ' + url);
                    }]);
                }.bind(this));
        },
```

Because the user isn't authorized to use the SiteImprove controller the ajax request will be forwarded to the login page and the __epiXSRF cookie will be invalidated.
![image](https://user-images.githubusercontent.com/17810399/32274732-8921bba2-bf08-11e7-9b43-4b7c47c1f91b.png)

Episerver will now tell the user that it's offline and has to manually log out and log in again to continue working in the Episerver UI.

Stacktrace: 

> Error message
System.InvalidOperationException: This request has probably been tampered with. Close the browser and try again.

>Stack trace
System.InvalidOperationException: This request has probably been tampered with. Close the browser and try again.
at EPiServer.Framework.Web.AspNetAntiForgery.ThrowForgeryException()
at EPiServer.Shell.Services.Rest.RestHttpHandler.ValidateAntiForgeryToken(HttpContextBase httpContext)
at EPiServer.Shell.Services.Rest.RestHttpHandler.GetController(HttpContextBase httpContext)
at EPiServer.Shell.Services.Rest.RestHttpHandler.BeginProcessRequest(HttpContextBase context, AsyncCallback callback, Object extraData)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by CasperTDK** [comment]
Thanks! We are now doing an auth check in the frontend/UI before contacting siteimprove

**Comment by CasperTDK** [comment]
Please await SiteImprove.EPiServer.Plugin.2.2.1 on nuget.http://nuget.episerver.com/
We are awaiting approval
