### ISSUE TITLE
Plugin not working with CMS 11.3.2

### ISSUE THREAD

**Issue by Drol** [Siteimprove/CMS-plugin-Episerver#7]
Sorry for the none English error message. But basically it can't load EPiServer.PlugIn.GuiPlugInAttribute. https://world.episerver.com/forum/developer-forum/-Episerver-75-CMS/Thread-Container/2017/12/could-not-load-type-episerver-plugin-guipluginattribute-from-assembly/ should be related.

`[TypeLoadException: Det gick inte att läsa in typen EPiServer.PlugIn.GuiPlugInAttribute från sammansättningen EPiServer, Version=11.3.2.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7.]
   System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) +0
   System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) +240
   System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) +161
   System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) +148
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent) +732
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) +403
   EPiServer.Framework.Initialization.<>c.<ScanAssemblies>b__46_0(Type t) +31
   System.Linq.WhereEnumerableIterator`1.MoveNext() +123
   System.Linq.<DistinctIterator>d__63`1.MoveNext() +79
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +263
   System.Linq.<CastIterator>d__94`1.MoveNext() +74
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +504
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +70
   EPiServer.Framework.Initialization.InitializationEngine.ScanAssemblies() +368
   EPiServer.Framework.Initialization.InitializationEngine.Initialize() +34
   EPiServer.Framework.Initialization.InitializationModule.EngineExecute(HostType hostType, Action`1 engineAction) +435
   EPiServer.Framework.Initialization.InitializationModule.FrameworkInitialization(HostType hostType) +227
   EPiServer.Global..ctor() +103
   Haninge.Web.EPiServerApplication..ctor() +43
   ASP.global_asax..ctor() +48`

**Comment by eripe** [comment]
I forked the repo and upgrade to cms11. Looks like it is working. Did a pull request as well.

**Comment by nma1o1** [comment]
We will have a look at it.

**Comment by Drol** [comment]
Any status on this?

**Comment by CasperTDK** [comment]
See: https://github.com/Siteimprove/CMS-plugin-Episerver/pull/8

:)
